// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Block.proto

public final class BlockProto {
  private BlockProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Block)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string timeStamp = 1;</code>
     * @return Whether the timeStamp field is set.
     */
    boolean hasTimeStamp();
    /**
     * <code>required string timeStamp = 1;</code>
     * @return The timeStamp.
     */
    java.lang.String getTimeStamp();
    /**
     * <code>required string timeStamp = 1;</code>
     * @return The bytes for timeStamp.
     */
    com.google.protobuf.ByteString
        getTimeStampBytes();

    /**
     * <code>required int64 nonce = 2;</code>
     * @return Whether the nonce field is set.
     */
    boolean hasNonce();
    /**
     * <code>required int64 nonce = 2;</code>
     * @return The nonce.
     */
    long getNonce();

    /**
     * <code>required bytes transactions = 3;</code>
     * @return Whether the transactions field is set.
     */
    boolean hasTransactions();
    /**
     * <code>required bytes transactions = 3;</code>
     * @return The transactions.
     */
    com.google.protobuf.ByteString getTransactions();

    /**
     * <code>required bytes prevBlockHash = 4;</code>
     * @return Whether the prevBlockHash field is set.
     */
    boolean hasPrevBlockHash();
    /**
     * <code>required bytes prevBlockHash = 4;</code>
     * @return The prevBlockHash.
     */
    com.google.protobuf.ByteString getPrevBlockHash();

    /**
     * <code>required bytes hash = 5;</code>
     * @return Whether the hash field is set.
     */
    boolean hasHash();
    /**
     * <code>required bytes hash = 5;</code>
     * @return The hash.
     */
    com.google.protobuf.ByteString getHash();
  }
  /**
   * Protobuf type {@code Block}
   */
  public static final class Block extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Block)
      BlockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Block.newBuilder() to construct.
    private Block(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Block() {
      timeStamp_ = "";
      transactions_ = com.google.protobuf.ByteString.EMPTY;
      prevBlockHash_ = com.google.protobuf.ByteString.EMPTY;
      hash_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Block();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Block(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              timeStamp_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              nonce_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              transactions_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              prevBlockHash_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              hash_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BlockProto.internal_static_Block_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BlockProto.internal_static_Block_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BlockProto.Block.class, BlockProto.Block.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private volatile java.lang.Object timeStamp_;
    /**
     * <code>required string timeStamp = 1;</code>
     * @return Whether the timeStamp field is set.
     */
    @java.lang.Override
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string timeStamp = 1;</code>
     * @return The timeStamp.
     */
    @java.lang.Override
    public java.lang.String getTimeStamp() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timeStamp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string timeStamp = 1;</code>
     * @return The bytes for timeStamp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NONCE_FIELD_NUMBER = 2;
    private long nonce_;
    /**
     * <code>required int64 nonce = 2;</code>
     * @return Whether the nonce field is set.
     */
    @java.lang.Override
    public boolean hasNonce() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int64 nonce = 2;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public long getNonce() {
      return nonce_;
    }

    public static final int TRANSACTIONS_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString transactions_;
    /**
     * <code>required bytes transactions = 3;</code>
     * @return Whether the transactions field is set.
     */
    @java.lang.Override
    public boolean hasTransactions() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required bytes transactions = 3;</code>
     * @return The transactions.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTransactions() {
      return transactions_;
    }

    public static final int PREVBLOCKHASH_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString prevBlockHash_;
    /**
     * <code>required bytes prevBlockHash = 4;</code>
     * @return Whether the prevBlockHash field is set.
     */
    @java.lang.Override
    public boolean hasPrevBlockHash() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required bytes prevBlockHash = 4;</code>
     * @return The prevBlockHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPrevBlockHash() {
      return prevBlockHash_;
    }

    public static final int HASH_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString hash_;
    /**
     * <code>required bytes hash = 5;</code>
     * @return Whether the hash field is set.
     */
    @java.lang.Override
    public boolean hasHash() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required bytes hash = 5;</code>
     * @return The hash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNonce()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransactions()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrevBlockHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timeStamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, nonce_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(3, transactions_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, prevBlockHash_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBytes(5, hash_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, timeStamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, nonce_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, transactions_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, prevBlockHash_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, hash_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BlockProto.Block)) {
        return super.equals(obj);
      }
      BlockProto.Block other = (BlockProto.Block) obj;

      if (hasTimeStamp() != other.hasTimeStamp()) return false;
      if (hasTimeStamp()) {
        if (!getTimeStamp()
            .equals(other.getTimeStamp())) return false;
      }
      if (hasNonce() != other.hasNonce()) return false;
      if (hasNonce()) {
        if (getNonce()
            != other.getNonce()) return false;
      }
      if (hasTransactions() != other.hasTransactions()) return false;
      if (hasTransactions()) {
        if (!getTransactions()
            .equals(other.getTransactions())) return false;
      }
      if (hasPrevBlockHash() != other.hasPrevBlockHash()) return false;
      if (hasPrevBlockHash()) {
        if (!getPrevBlockHash()
            .equals(other.getPrevBlockHash())) return false;
      }
      if (hasHash() != other.hasHash()) return false;
      if (hasHash()) {
        if (!getHash()
            .equals(other.getHash())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimeStamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimeStamp().hashCode();
      }
      if (hasNonce()) {
        hash = (37 * hash) + NONCE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNonce());
      }
      if (hasTransactions()) {
        hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getTransactions().hashCode();
      }
      if (hasPrevBlockHash()) {
        hash = (37 * hash) + PREVBLOCKHASH_FIELD_NUMBER;
        hash = (53 * hash) + getPrevBlockHash().hashCode();
      }
      if (hasHash()) {
        hash = (37 * hash) + HASH_FIELD_NUMBER;
        hash = (53 * hash) + getHash().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BlockProto.Block parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BlockProto.Block parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BlockProto.Block parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BlockProto.Block parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BlockProto.Block parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BlockProto.Block parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BlockProto.Block parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BlockProto.Block parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BlockProto.Block parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BlockProto.Block parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BlockProto.Block parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BlockProto.Block parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BlockProto.Block prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Block}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Block)
        BlockProto.BlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BlockProto.internal_static_Block_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BlockProto.internal_static_Block_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BlockProto.Block.class, BlockProto.Block.Builder.class);
      }

      // Construct using BlockProto.Block.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timeStamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nonce_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        transactions_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        prevBlockHash_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        hash_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BlockProto.internal_static_Block_descriptor;
      }

      @java.lang.Override
      public BlockProto.Block getDefaultInstanceForType() {
        return BlockProto.Block.getDefaultInstance();
      }

      @java.lang.Override
      public BlockProto.Block build() {
        BlockProto.Block result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public BlockProto.Block buildPartial() {
        BlockProto.Block result = new BlockProto.Block(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.nonce_ = nonce_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.transactions_ = transactions_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.prevBlockHash_ = prevBlockHash_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.hash_ = hash_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BlockProto.Block) {
          return mergeFrom((BlockProto.Block)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BlockProto.Block other) {
        if (other == BlockProto.Block.getDefaultInstance()) return this;
        if (other.hasTimeStamp()) {
          bitField0_ |= 0x00000001;
          timeStamp_ = other.timeStamp_;
          onChanged();
        }
        if (other.hasNonce()) {
          setNonce(other.getNonce());
        }
        if (other.hasTransactions()) {
          setTransactions(other.getTransactions());
        }
        if (other.hasPrevBlockHash()) {
          setPrevBlockHash(other.getPrevBlockHash());
        }
        if (other.hasHash()) {
          setHash(other.getHash());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTimeStamp()) {
          return false;
        }
        if (!hasNonce()) {
          return false;
        }
        if (!hasTransactions()) {
          return false;
        }
        if (!hasPrevBlockHash()) {
          return false;
        }
        if (!hasHash()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BlockProto.Block parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BlockProto.Block) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object timeStamp_ = "";
      /**
       * <code>required string timeStamp = 1;</code>
       * @return Whether the timeStamp field is set.
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string timeStamp = 1;</code>
       * @return The timeStamp.
       */
      public java.lang.String getTimeStamp() {
        java.lang.Object ref = timeStamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timeStamp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string timeStamp = 1;</code>
       * @return The bytes for timeStamp.
       */
      public com.google.protobuf.ByteString
          getTimeStampBytes() {
        java.lang.Object ref = timeStamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeStamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string timeStamp = 1;</code>
       * @param value The timeStamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimeStamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string timeStamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timeStamp_ = getDefaultInstance().getTimeStamp();
        onChanged();
        return this;
      }
      /**
       * <code>required string timeStamp = 1;</code>
       * @param value The bytes for timeStamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimeStampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        timeStamp_ = value;
        onChanged();
        return this;
      }

      private long nonce_ ;
      /**
       * <code>required int64 nonce = 2;</code>
       * @return Whether the nonce field is set.
       */
      @java.lang.Override
      public boolean hasNonce() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int64 nonce = 2;</code>
       * @return The nonce.
       */
      @java.lang.Override
      public long getNonce() {
        return nonce_;
      }
      /**
       * <code>required int64 nonce = 2;</code>
       * @param value The nonce to set.
       * @return This builder for chaining.
       */
      public Builder setNonce(long value) {
        bitField0_ |= 0x00000002;
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 nonce = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNonce() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nonce_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString transactions_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes transactions = 3;</code>
       * @return Whether the transactions field is set.
       */
      @java.lang.Override
      public boolean hasTransactions() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required bytes transactions = 3;</code>
       * @return The transactions.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTransactions() {
        return transactions_;
      }
      /**
       * <code>required bytes transactions = 3;</code>
       * @param value The transactions to set.
       * @return This builder for chaining.
       */
      public Builder setTransactions(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        transactions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes transactions = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransactions() {
        bitField0_ = (bitField0_ & ~0x00000004);
        transactions_ = getDefaultInstance().getTransactions();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString prevBlockHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes prevBlockHash = 4;</code>
       * @return Whether the prevBlockHash field is set.
       */
      @java.lang.Override
      public boolean hasPrevBlockHash() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required bytes prevBlockHash = 4;</code>
       * @return The prevBlockHash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPrevBlockHash() {
        return prevBlockHash_;
      }
      /**
       * <code>required bytes prevBlockHash = 4;</code>
       * @param value The prevBlockHash to set.
       * @return This builder for chaining.
       */
      public Builder setPrevBlockHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        prevBlockHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes prevBlockHash = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrevBlockHash() {
        bitField0_ = (bitField0_ & ~0x00000008);
        prevBlockHash_ = getDefaultInstance().getPrevBlockHash();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes hash = 5;</code>
       * @return Whether the hash field is set.
       */
      @java.lang.Override
      public boolean hasHash() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required bytes hash = 5;</code>
       * @return The hash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getHash() {
        return hash_;
      }
      /**
       * <code>required bytes hash = 5;</code>
       * @param value The hash to set.
       * @return This builder for chaining.
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes hash = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHash() {
        bitField0_ = (bitField0_ & ~0x00000010);
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Block)
    }

    // @@protoc_insertion_point(class_scope:Block)
    private static final BlockProto.Block DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BlockProto.Block();
    }

    public static BlockProto.Block getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Block>
        PARSER = new com.google.protobuf.AbstractParser<Block>() {
      @java.lang.Override
      public Block parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Block(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Block> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Block> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public BlockProto.Block getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Block_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Block_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Block.proto\"d\n\005Block\022\021\n\ttimeStamp\030\001 \002(" +
      "\t\022\r\n\005nonce\030\002 \002(\003\022\024\n\014transactions\030\003 \002(\014\022\025" +
      "\n\rprevBlockHash\030\004 \002(\014\022\014\n\004hash\030\005 \002(\014B\014B\nB" +
      "lockProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Block_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Block_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Block_descriptor,
        new java.lang.String[] { "TimeStamp", "Nonce", "Transactions", "PrevBlockHash", "Hash", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
