// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Block.proto

public final class BlockProto {
  private BlockProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Block)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string timeStamp = 1;</code>
     * @return Whether the timeStamp field is set.
     */
    boolean hasTimeStamp();
    /**
     * <code>required string timeStamp = 1;</code>
     * @return The timeStamp.
     */
    java.lang.String getTimeStamp();
    /**
     * <code>required string timeStamp = 1;</code>
     * @return The bytes for timeStamp.
     */
    com.google.protobuf.ByteString
        getTimeStampBytes();

    /**
     * <code>required int64 nonce = 2;</code>
     * @return Whether the nonce field is set.
     */
    boolean hasNonce();
    /**
     * <code>required int64 nonce = 2;</code>
     * @return The nonce.
     */
    long getNonce();

    /**
     * <code>repeated bytes data = 3;</code>
     * @return A list containing the data.
     */
    java.util.List<com.google.protobuf.ByteString> getDataList();
    /**
     * <code>repeated bytes data = 3;</code>
     * @return The count of data.
     */
    int getDataCount();
    /**
     * <code>repeated bytes data = 3;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    com.google.protobuf.ByteString getData(int index);

    /**
     * <code>repeated bytes prevBlockHash = 4;</code>
     * @return A list containing the prevBlockHash.
     */
    java.util.List<com.google.protobuf.ByteString> getPrevBlockHashList();
    /**
     * <code>repeated bytes prevBlockHash = 4;</code>
     * @return The count of prevBlockHash.
     */
    int getPrevBlockHashCount();
    /**
     * <code>repeated bytes prevBlockHash = 4;</code>
     * @param index The index of the element to return.
     * @return The prevBlockHash at the given index.
     */
    com.google.protobuf.ByteString getPrevBlockHash(int index);

    /**
     * <code>repeated bytes hash = 5;</code>
     * @return A list containing the hash.
     */
    java.util.List<com.google.protobuf.ByteString> getHashList();
    /**
     * <code>repeated bytes hash = 5;</code>
     * @return The count of hash.
     */
    int getHashCount();
    /**
     * <code>repeated bytes hash = 5;</code>
     * @param index The index of the element to return.
     * @return The hash at the given index.
     */
    com.google.protobuf.ByteString getHash(int index);
  }
  /**
   * Protobuf type {@code Block}
   */
  public static final class Block extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Block)
      BlockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Block.newBuilder() to construct.
    private Block(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Block() {
      timeStamp_ = "";
      data_ = java.util.Collections.emptyList();
      prevBlockHash_ = java.util.Collections.emptyList();
      hash_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Block();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Block(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              timeStamp_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              nonce_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                data_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000004;
              }
              data_.add(input.readBytes());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                prevBlockHash_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000008;
              }
              prevBlockHash_.add(input.readBytes());
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                hash_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000010;
              }
              hash_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_); // C
        }
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          prevBlockHash_ = java.util.Collections.unmodifiableList(prevBlockHash_); // C
        }
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          hash_ = java.util.Collections.unmodifiableList(hash_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BlockProto.internal_static_Block_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BlockProto.internal_static_Block_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BlockProto.Block.class, BlockProto.Block.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private volatile java.lang.Object timeStamp_;
    /**
     * <code>required string timeStamp = 1;</code>
     * @return Whether the timeStamp field is set.
     */
    @java.lang.Override
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string timeStamp = 1;</code>
     * @return The timeStamp.
     */
    @java.lang.Override
    public java.lang.String getTimeStamp() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timeStamp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string timeStamp = 1;</code>
     * @return The bytes for timeStamp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NONCE_FIELD_NUMBER = 2;
    private long nonce_;
    /**
     * <code>required int64 nonce = 2;</code>
     * @return Whether the nonce field is set.
     */
    @java.lang.Override
    public boolean hasNonce() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int64 nonce = 2;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public long getNonce() {
      return nonce_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> data_;
    /**
     * <code>repeated bytes data = 3;</code>
     * @return A list containing the data.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated bytes data = 3;</code>
     * @return The count of data.
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated bytes data = 3;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    public com.google.protobuf.ByteString getData(int index) {
      return data_.get(index);
    }

    public static final int PREVBLOCKHASH_FIELD_NUMBER = 4;
    private java.util.List<com.google.protobuf.ByteString> prevBlockHash_;
    /**
     * <code>repeated bytes prevBlockHash = 4;</code>
     * @return A list containing the prevBlockHash.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getPrevBlockHashList() {
      return prevBlockHash_;
    }
    /**
     * <code>repeated bytes prevBlockHash = 4;</code>
     * @return The count of prevBlockHash.
     */
    public int getPrevBlockHashCount() {
      return prevBlockHash_.size();
    }
    /**
     * <code>repeated bytes prevBlockHash = 4;</code>
     * @param index The index of the element to return.
     * @return The prevBlockHash at the given index.
     */
    public com.google.protobuf.ByteString getPrevBlockHash(int index) {
      return prevBlockHash_.get(index);
    }

    public static final int HASH_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.ByteString> hash_;
    /**
     * <code>repeated bytes hash = 5;</code>
     * @return A list containing the hash.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getHashList() {
      return hash_;
    }
    /**
     * <code>repeated bytes hash = 5;</code>
     * @return The count of hash.
     */
    public int getHashCount() {
      return hash_.size();
    }
    /**
     * <code>repeated bytes hash = 5;</code>
     * @param index The index of the element to return.
     * @return The hash at the given index.
     */
    public com.google.protobuf.ByteString getHash(int index) {
      return hash_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNonce()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timeStamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, nonce_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeBytes(3, data_.get(i));
      }
      for (int i = 0; i < prevBlockHash_.size(); i++) {
        output.writeBytes(4, prevBlockHash_.get(i));
      }
      for (int i = 0; i < hash_.size(); i++) {
        output.writeBytes(5, hash_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, timeStamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, nonce_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(data_.get(i));
        }
        size += dataSize;
        size += 1 * getDataList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < prevBlockHash_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(prevBlockHash_.get(i));
        }
        size += dataSize;
        size += 1 * getPrevBlockHashList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < hash_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(hash_.get(i));
        }
        size += dataSize;
        size += 1 * getHashList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BlockProto.Block)) {
        return super.equals(obj);
      }
      BlockProto.Block other = (BlockProto.Block) obj;

      if (hasTimeStamp() != other.hasTimeStamp()) return false;
      if (hasTimeStamp()) {
        if (!getTimeStamp()
            .equals(other.getTimeStamp())) return false;
      }
      if (hasNonce() != other.hasNonce()) return false;
      if (hasNonce()) {
        if (getNonce()
            != other.getNonce()) return false;
      }
      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!getPrevBlockHashList()
          .equals(other.getPrevBlockHashList())) return false;
      if (!getHashList()
          .equals(other.getHashList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimeStamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimeStamp().hashCode();
      }
      if (hasNonce()) {
        hash = (37 * hash) + NONCE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNonce());
      }
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      if (getPrevBlockHashCount() > 0) {
        hash = (37 * hash) + PREVBLOCKHASH_FIELD_NUMBER;
        hash = (53 * hash) + getPrevBlockHashList().hashCode();
      }
      if (getHashCount() > 0) {
        hash = (37 * hash) + HASH_FIELD_NUMBER;
        hash = (53 * hash) + getHashList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BlockProto.Block parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BlockProto.Block parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BlockProto.Block parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BlockProto.Block parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BlockProto.Block parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BlockProto.Block parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BlockProto.Block parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BlockProto.Block parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BlockProto.Block parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BlockProto.Block parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BlockProto.Block parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BlockProto.Block parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BlockProto.Block prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Block}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Block)
        BlockProto.BlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BlockProto.internal_static_Block_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BlockProto.internal_static_Block_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BlockProto.Block.class, BlockProto.Block.Builder.class);
      }

      // Construct using BlockProto.Block.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timeStamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nonce_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        prevBlockHash_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        hash_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BlockProto.internal_static_Block_descriptor;
      }

      @java.lang.Override
      public BlockProto.Block getDefaultInstanceForType() {
        return BlockProto.Block.getDefaultInstance();
      }

      @java.lang.Override
      public BlockProto.Block build() {
        BlockProto.Block result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public BlockProto.Block buildPartial() {
        BlockProto.Block result = new BlockProto.Block(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.nonce_ = nonce_;
          to_bitField0_ |= 0x00000002;
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.data_ = data_;
        if (((bitField0_ & 0x00000008) != 0)) {
          prevBlockHash_ = java.util.Collections.unmodifiableList(prevBlockHash_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.prevBlockHash_ = prevBlockHash_;
        if (((bitField0_ & 0x00000010) != 0)) {
          hash_ = java.util.Collections.unmodifiableList(hash_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.hash_ = hash_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BlockProto.Block) {
          return mergeFrom((BlockProto.Block)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BlockProto.Block other) {
        if (other == BlockProto.Block.getDefaultInstance()) return this;
        if (other.hasTimeStamp()) {
          bitField0_ |= 0x00000001;
          timeStamp_ = other.timeStamp_;
          onChanged();
        }
        if (other.hasNonce()) {
          setNonce(other.getNonce());
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        if (!other.prevBlockHash_.isEmpty()) {
          if (prevBlockHash_.isEmpty()) {
            prevBlockHash_ = other.prevBlockHash_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePrevBlockHashIsMutable();
            prevBlockHash_.addAll(other.prevBlockHash_);
          }
          onChanged();
        }
        if (!other.hash_.isEmpty()) {
          if (hash_.isEmpty()) {
            hash_ = other.hash_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureHashIsMutable();
            hash_.addAll(other.hash_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTimeStamp()) {
          return false;
        }
        if (!hasNonce()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BlockProto.Block parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BlockProto.Block) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object timeStamp_ = "";
      /**
       * <code>required string timeStamp = 1;</code>
       * @return Whether the timeStamp field is set.
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string timeStamp = 1;</code>
       * @return The timeStamp.
       */
      public java.lang.String getTimeStamp() {
        java.lang.Object ref = timeStamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timeStamp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string timeStamp = 1;</code>
       * @return The bytes for timeStamp.
       */
      public com.google.protobuf.ByteString
          getTimeStampBytes() {
        java.lang.Object ref = timeStamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeStamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string timeStamp = 1;</code>
       * @param value The timeStamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimeStamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string timeStamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timeStamp_ = getDefaultInstance().getTimeStamp();
        onChanged();
        return this;
      }
      /**
       * <code>required string timeStamp = 1;</code>
       * @param value The bytes for timeStamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimeStampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        timeStamp_ = value;
        onChanged();
        return this;
      }

      private long nonce_ ;
      /**
       * <code>required int64 nonce = 2;</code>
       * @return Whether the nonce field is set.
       */
      @java.lang.Override
      public boolean hasNonce() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int64 nonce = 2;</code>
       * @return The nonce.
       */
      @java.lang.Override
      public long getNonce() {
        return nonce_;
      }
      /**
       * <code>required int64 nonce = 2;</code>
       * @param value The nonce to set.
       * @return This builder for chaining.
       */
      public Builder setNonce(long value) {
        bitField0_ |= 0x00000002;
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 nonce = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNonce() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nonce_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> data_ = java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          data_ = new java.util.ArrayList<com.google.protobuf.ByteString>(data_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated bytes data = 3;</code>
       * @return A list containing the data.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getDataList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(data_) : data_;
      }
      /**
       * <code>repeated bytes data = 3;</code>
       * @return The count of data.
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated bytes data = 3;</code>
       * @param index The index of the element to return.
       * @return The data at the given index.
       */
      public com.google.protobuf.ByteString getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated bytes data = 3;</code>
       * @param index The index to set the value at.
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes data = 3;</code>
       * @param value The data to add.
       * @return This builder for chaining.
       */
      public Builder addData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes data = 3;</code>
       * @param values The data to add.
       * @return This builder for chaining.
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> prevBlockHash_ = java.util.Collections.emptyList();
      private void ensurePrevBlockHashIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          prevBlockHash_ = new java.util.ArrayList<com.google.protobuf.ByteString>(prevBlockHash_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated bytes prevBlockHash = 4;</code>
       * @return A list containing the prevBlockHash.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getPrevBlockHashList() {
        return ((bitField0_ & 0x00000008) != 0) ?
                 java.util.Collections.unmodifiableList(prevBlockHash_) : prevBlockHash_;
      }
      /**
       * <code>repeated bytes prevBlockHash = 4;</code>
       * @return The count of prevBlockHash.
       */
      public int getPrevBlockHashCount() {
        return prevBlockHash_.size();
      }
      /**
       * <code>repeated bytes prevBlockHash = 4;</code>
       * @param index The index of the element to return.
       * @return The prevBlockHash at the given index.
       */
      public com.google.protobuf.ByteString getPrevBlockHash(int index) {
        return prevBlockHash_.get(index);
      }
      /**
       * <code>repeated bytes prevBlockHash = 4;</code>
       * @param index The index to set the value at.
       * @param value The prevBlockHash to set.
       * @return This builder for chaining.
       */
      public Builder setPrevBlockHash(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePrevBlockHashIsMutable();
        prevBlockHash_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes prevBlockHash = 4;</code>
       * @param value The prevBlockHash to add.
       * @return This builder for chaining.
       */
      public Builder addPrevBlockHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePrevBlockHashIsMutable();
        prevBlockHash_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes prevBlockHash = 4;</code>
       * @param values The prevBlockHash to add.
       * @return This builder for chaining.
       */
      public Builder addAllPrevBlockHash(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensurePrevBlockHashIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, prevBlockHash_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes prevBlockHash = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrevBlockHash() {
        prevBlockHash_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> hash_ = java.util.Collections.emptyList();
      private void ensureHashIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          hash_ = new java.util.ArrayList<com.google.protobuf.ByteString>(hash_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated bytes hash = 5;</code>
       * @return A list containing the hash.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getHashList() {
        return ((bitField0_ & 0x00000010) != 0) ?
                 java.util.Collections.unmodifiableList(hash_) : hash_;
      }
      /**
       * <code>repeated bytes hash = 5;</code>
       * @return The count of hash.
       */
      public int getHashCount() {
        return hash_.size();
      }
      /**
       * <code>repeated bytes hash = 5;</code>
       * @param index The index of the element to return.
       * @return The hash at the given index.
       */
      public com.google.protobuf.ByteString getHash(int index) {
        return hash_.get(index);
      }
      /**
       * <code>repeated bytes hash = 5;</code>
       * @param index The index to set the value at.
       * @param value The hash to set.
       * @return This builder for chaining.
       */
      public Builder setHash(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHashIsMutable();
        hash_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes hash = 5;</code>
       * @param value The hash to add.
       * @return This builder for chaining.
       */
      public Builder addHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHashIsMutable();
        hash_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes hash = 5;</code>
       * @param values The hash to add.
       * @return This builder for chaining.
       */
      public Builder addAllHash(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureHashIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hash_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes hash = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHash() {
        hash_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Block)
    }

    // @@protoc_insertion_point(class_scope:Block)
    private static final BlockProto.Block DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BlockProto.Block();
    }

    public static BlockProto.Block getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Block>
        PARSER = new com.google.protobuf.AbstractParser<Block>() {
      @java.lang.Override
      public Block parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Block(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Block> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Block> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public BlockProto.Block getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Block_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Block_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Block.proto\"\\\n\005Block\022\021\n\ttimeStamp\030\001 \002(" +
      "\t\022\r\n\005nonce\030\002 \002(\003\022\014\n\004data\030\003 \003(\014\022\025\n\rprevBl" +
      "ockHash\030\004 \003(\014\022\014\n\004hash\030\005 \003(\014B\014B\nBlockProt" +
      "o"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Block_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Block_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Block_descriptor,
        new java.lang.String[] { "TimeStamp", "Nonce", "Data", "PrevBlockHash", "Hash", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
